# Generated by Django 4.1.2 on 2022-10-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFabrica', '0003_prospecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='legajo',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='mayorista',
            name='apellido',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='mayorista',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='mayorista',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='mayorista',
            name='telefono',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='zapato',
            name='color',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='zapato',
            name='material',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='zapato',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='zapato',
            name='precio',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='zapato',
            name='stock',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='zapato',
            name='talle',
            field=models.IntegerField(default=None),
        ),
    ]
